create database Projetin_Condominio_Edson;
Use Projetin_Condominio_Edson;

CREATE TABLE PRODUTO_ENCOMENDA(
COD_PROD VARCHAR (10) PRIMARY KEY, 
CPF_RESPONSAVEL NUMERIC (11),
NOME_RESPONSAVEL VARCHAR (55), 
DATA_HORA_CHEGADA DATETIME,
DATA_HORA_SAIDA DATETIME 
);

INSERT INTO PRODUTO_ENCOMENDA VALUES (01, 69845612305, 'Clara Diaz', GETDATE(), GETDATE()); 
INSERT INTO PRODUTO_ENCOMENDA VALUES(02, 85497632145, 'Luis Alberto', GETDATE (), GETDATE());

SELECT * FROM PRODUTO_ENCOMENDA;
SELECT NOME_RESPONSAVEL, CPF_RESPONSAVEL FROM PRODUTO_ENCOMENDA WHERE COD_PROD = 01;
SELECT NOME_RESPONSAVEL, CPF_RESPONSAVEL, DATA_HORA_CHEGADA, DATA_HORA_SAIDA FROM PRODUTO_ENCOMENDA WHERE COD_PROD = 02;
